<?php
/**
 * Conecta ERP - Configuración de Países
 * 12 países soportados con configuración completa
 */

return [
    'CL' => [
        'name' => 'Chile',
        'code' => 'CL',
        'identifier_type' => 'RUT',
        'identifier_format' => 'XX.XXX.XXX-X',
        'identifier_regex' => '/^[0-9]{1,2}\.[0-9]{3}\.[0-9]{3}-[0-9Kk]$/',
        'identifier_example' => '12.345.678-9',
        'currency' => 'CLP',
        'currency_symbol' => '$',
        'date_format' => 'DD/MM/YYYY',
        'date_format_php' => 'd/m/Y',
        'timezone' => 'America/Santiago',
        'decimal_separator' => ',',
        'thousands_separator' => '.',
        'tax_name' => 'IVA',
        'tax_rate' => 19.00,
        'tax_id_format' => 'RUT',
        'integrations' => [
            'sii' => true,
            'previred' => true,
            'tax_authority' => 'SII',
            'social_security' => 'Previred',
        ],
        'documents' => [
            'invoice' => 'Factura Electrónica',
            'receipt' => 'Boleta Electrónica',
            'credit_note' => 'Nota de Crédito',
            'debit_note' => 'Nota de Débito',
            'delivery_note' => 'Guía de Despacho',
        ],
        'phone_code' => '+56',
        'locale' => 'es_CL',
        'enabled' => true,
    ],

    'AR' => [
        'name' => 'Argentina',
        'code' => 'AR',
        'identifier_type' => 'CUIT',
        'identifier_format' => 'XX-XXXXXXXX-X',
        'identifier_regex' => '/^[0-9]{2}-[0-9]{8}-[0-9]$/',
        'identifier_example' => '20-12345678-9',
        'currency' => 'ARS',
        'currency_symbol' => '$',
        'date_format' => 'DD/MM/YYYY',
        'date_format_php' => 'd/m/Y',
        'timezone' => 'America/Buenos_Aires',
        'decimal_separator' => ',',
        'thousands_separator' => '.',
        'tax_name' => 'IVA',
        'tax_rate' => 21.00,
        'tax_id_format' => 'CUIT',
        'integrations' => [
            'afip' => true,
            'tax_authority' => 'AFIP',
        ],
        'documents' => [
            'invoice' => 'Factura Electrónica',
            'receipt' => 'Recibo',
            'credit_note' => 'Nota de Crédito',
            'debit_note' => 'Nota de Débito',
        ],
        'phone_code' => '+54',
        'locale' => 'es_AR',
        'enabled' => true,
    ],

    'PE' => [
        'name' => 'Perú',
        'code' => 'PE',
        'identifier_type' => 'RUC',
        'identifier_format' => 'XXXXXXXXXXX',
        'identifier_regex' => '/^[0-9]{11}$/',
        'identifier_example' => '20123456789',
        'currency' => 'PEN',
        'currency_symbol' => 'S/',
        'date_format' => 'DD/MM/YYYY',
        'date_format_php' => 'd/m/Y',
        'timezone' => 'America/Lima',
        'decimal_separator' => '.',
        'thousands_separator' => ',',
        'tax_name' => 'IGV',
        'tax_rate' => 18.00,
        'tax_id_format' => 'RUC',
        'integrations' => [
            'sunat' => true,
            'tax_authority' => 'SUNAT',
        ],
        'documents' => [
            'invoice' => 'Factura Electrónica',
            'receipt' => 'Boleta de Venta',
            'credit_note' => 'Nota de Crédito',
            'debit_note' => 'Nota de Débito',
        ],
        'phone_code' => '+51',
        'locale' => 'es_PE',
        'enabled' => true,
    ],

    'CO' => [
        'name' => 'Colombia',
        'code' => 'CO',
        'identifier_type' => 'NIT',
        'identifier_format' => 'XXXXXXXX-X',
        'identifier_regex' => '/^[0-9]{8,10}-[0-9]$/',
        'identifier_example' => '12345678-9',
        'currency' => 'COP',
        'currency_symbol' => '$',
        'date_format' => 'DD/MM/YYYY',
        'date_format_php' => 'd/m/Y',
        'timezone' => 'America/Bogota',
        'decimal_separator' => ',',
        'thousands_separator' => '.',
        'tax_name' => 'IVA',
        'tax_rate' => 19.00,
        'tax_id_format' => 'NIT',
        'integrations' => [
            'dian' => true,
            'tax_authority' => 'DIAN',
        ],
        'documents' => [
            'invoice' => 'Factura Electrónica',
            'receipt' => 'Recibo',
            'credit_note' => 'Nota Crédito',
            'debit_note' => 'Nota Débito',
        ],
        'phone_code' => '+57',
        'locale' => 'es_CO',
        'enabled' => true,
    ],

    'MX' => [
        'name' => 'México',
        'code' => 'MX',
        'identifier_type' => 'RFC',
        'identifier_format' => 'XXXX000000XXX',
        'identifier_regex' => '/^[A-ZÑ&]{3,4}[0-9]{6}[A-Z0-9]{3}$/',
        'identifier_example' => 'ABC123456XYZ',
        'currency' => 'MXN',
        'currency_symbol' => '$',
        'date_format' => 'DD/MM/YYYY',
        'date_format_php' => 'd/m/Y',
        'timezone' => 'America/Mexico_City',
        'decimal_separator' => '.',
        'thousands_separator' => ',',
        'tax_name' => 'IVA',
        'tax_rate' => 16.00,
        'tax_id_format' => 'RFC',
        'integrations' => [
            'sat' => true,
            'tax_authority' => 'SAT',
        ],
        'documents' => [
            'invoice' => 'CFDI',
            'receipt' => 'Recibo',
            'credit_note' => 'Nota de Crédito',
        ],
        'phone_code' => '+52',
        'locale' => 'es_MX',
        'enabled' => true,
    ],

    'BR' => [
        'name' => 'Brasil',
        'code' => 'BR',
        'identifier_type' => 'CNPJ',
        'identifier_format' => 'XX.XXX.XXX/0001-XX',
        'identifier_regex' => '/^[0-9]{2}\.[0-9]{3}\.[0-9]{3}\/[0-9]{4}-[0-9]{2}$/',
        'identifier_example' => '12.345.678/0001-90',
        'identifier_type_secondary' => 'CPF',
        'identifier_format_secondary' => 'XXX.XXX.XXX-XX',
        'currency' => 'BRL',
        'currency_symbol' => 'R$',
        'date_format' => 'DD/MM/YYYY',
        'date_format_php' => 'd/m/Y',
        'timezone' => 'America/Sao_Paulo',
        'decimal_separator' => ',',
        'thousands_separator' => '.',
        'tax_name' => 'ICMS/IPI',
        'tax_rate' => 18.00,
        'tax_id_format' => 'CNPJ',
        'integrations' => [
            'receita_federal' => true,
            'tax_authority' => 'Receita Federal',
        ],
        'documents' => [
            'invoice' => 'Nota Fiscal Eletrônica',
            'receipt' => 'Recibo',
        ],
        'phone_code' => '+55',
        'locale' => 'pt_BR',
        'enabled' => true,
    ],

    'US' => [
        'name' => 'Estados Unidos',
        'code' => 'US',
        'identifier_type' => 'EIN',
        'identifier_format' => 'XX-XXXXXXX',
        'identifier_regex' => '/^[0-9]{2}-[0-9]{7}$/',
        'identifier_example' => '12-3456789',
        'identifier_type_secondary' => 'SSN',
        'currency' => 'USD',
        'currency_symbol' => '$',
        'date_format' => 'MM/DD/YYYY',
        'date_format_php' => 'm/d/Y',
        'timezone' => 'America/New_York',
        'decimal_separator' => '.',
        'thousands_separator' => ',',
        'tax_name' => 'Sales Tax',
        'tax_rate' => 0.00, // Varía por estado
        'tax_id_format' => 'EIN',
        'integrations' => [
            'irs' => false,
            'tax_authority' => 'IRS',
        ],
        'documents' => [
            'invoice' => 'Invoice',
            'receipt' => 'Receipt',
        ],
        'phone_code' => '+1',
        'locale' => 'en_US',
        'enabled' => true,
    ],

    'ES' => [
        'name' => 'España',
        'code' => 'ES',
        'identifier_type' => 'CIF/NIF',
        'identifier_format' => 'X0000000X',
        'identifier_regex' => '/^[A-Z][0-9]{7}[A-Z0-9]$/',
        'identifier_example' => 'A12345678',
        'currency' => 'EUR',
        'currency_symbol' => '€',
        'date_format' => 'DD/MM/YYYY',
        'date_format_php' => 'd/m/Y',
        'timezone' => 'Europe/Madrid',
        'decimal_separator' => ',',
        'thousands_separator' => '.',
        'tax_name' => 'IVA',
        'tax_rate' => 21.00,
        'tax_id_format' => 'CIF',
        'integrations' => [
            'aeat' => true,
            'tax_authority' => 'AEAT',
        ],
        'documents' => [
            'invoice' => 'Factura Electrónica',
            'receipt' => 'Recibo',
        ],
        'phone_code' => '+34',
        'locale' => 'es_ES',
        'enabled' => true,
    ],

    'FR' => [
        'name' => 'Francia',
        'code' => 'FR',
        'identifier_type' => 'SIRET',
        'identifier_format' => 'XXXXXXXXXXXXXX',
        'identifier_regex' => '/^[0-9]{14}$/',
        'identifier_example' => '12345678901234',
        'currency' => 'EUR',
        'currency_symbol' => '€',
        'date_format' => 'DD/MM/YYYY',
        'date_format_php' => 'd/m/Y',
        'timezone' => 'Europe/Paris',
        'decimal_separator' => ',',
        'thousands_separator' => ' ',
        'tax_name' => 'TVA',
        'tax_rate' => 20.00,
        'tax_id_format' => 'SIRET',
        'integrations' => [],
        'documents' => [
            'invoice' => 'Facture',
            'receipt' => 'Reçu',
        ],
        'phone_code' => '+33',
        'locale' => 'fr_FR',
        'enabled' => true,
    ],

    'DE' => [
        'name' => 'Alemania',
        'code' => 'DE',
        'identifier_type' => 'USt-IdNr',
        'identifier_format' => 'DEXXXXXXXXX',
        'identifier_regex' => '/^DE[0-9]{9}$/',
        'identifier_example' => 'DE123456789',
        'currency' => 'EUR',
        'currency_symbol' => '€',
        'date_format' => 'DD.MM.YYYY',
        'date_format_php' => 'd.m.Y',
        'timezone' => 'Europe/Berlin',
        'decimal_separator' => ',',
        'thousands_separator' => '.',
        'tax_name' => 'MwSt',
        'tax_rate' => 19.00,
        'tax_id_format' => 'USt-IdNr',
        'integrations' => [],
        'documents' => [
            'invoice' => 'Rechnung',
            'receipt' => 'Quittung',
        ],
        'phone_code' => '+49',
        'locale' => 'de_DE',
        'enabled' => true,
    ],

    'IT' => [
        'name' => 'Italia',
        'code' => 'IT',
        'identifier_type' => 'Partita IVA',
        'identifier_format' => 'XXXXXXXXXXX',
        'identifier_regex' => '/^[0-9]{11}$/',
        'identifier_example' => '12345678901',
        'currency' => 'EUR',
        'currency_symbol' => '€',
        'date_format' => 'DD/MM/YYYY',
        'date_format_php' => 'd/m/Y',
        'timezone' => 'Europe/Rome',
        'decimal_separator' => ',',
        'thousands_separator' => '.',
        'tax_name' => 'IVA',
        'tax_rate' => 22.00,
        'tax_id_format' => 'Partita IVA',
        'integrations' => [],
        'documents' => [
            'invoice' => 'Fattura',
            'receipt' => 'Ricevuta',
        ],
        'phone_code' => '+39',
        'locale' => 'it_IT',
        'enabled' => true,
    ],

    'GB' => [
        'name' => 'Reino Unido',
        'code' => 'GB',
        'identifier_type' => 'VAT Number',
        'identifier_format' => 'GBXXXXXXXXX',
        'identifier_regex' => '/^GB[0-9]{9}$/',
        'identifier_example' => 'GB123456789',
        'currency' => 'GBP',
        'currency_symbol' => '£',
        'date_format' => 'DD/MM/YYYY',
        'date_format_php' => 'd/m/Y',
        'timezone' => 'Europe/London',
        'decimal_separator' => '.',
        'thousands_separator' => ',',
        'tax_name' => 'VAT',
        'tax_rate' => 20.00,
        'tax_id_format' => 'VAT Number',
        'integrations' => [],
        'documents' => [
            'invoice' => 'Invoice',
            'receipt' => 'Receipt',
        ],
        'phone_code' => '+44',
        'locale' => 'en_GB',
        'enabled' => true,
    ],
];
